Added: Event and Item as param in a callback
steviebaa/mui-nested-menu pull request #30
Opened 2023-01-02 17:50 UTC by YASHBRO

Added: Event and Item as param in a callback
Updated: type of callback in their respective interface

2023-01-11 21:39 UTC, steviebaa commented
Thanks for the PR @YASHBRO.

It looks like your formatter changed quite a bit - my fault for not including a `.prettierrc`.

I've added a prettier config file to the project, formatted everything and pushed it to main. Can you rebase your branch with main and just check there isn't unnecessary formatting changes in the PR.

Thanks

2023-01-12 17:22 UTC, YASHBRO commented
Hey @steviebaa 

I have rebased my branch with the main branch
Now in the _files changed_ tab, there are only necessary changes showing up

Let me know if there's any other change you want me to implement

2023-01-13 21:54 UTC, steviebaa requested changes
Just a few minor changes. 

Another note, when clicking the New item in the first dropdown on the [preview page](https://mui-nested-menu-6zkzw2lko-steviebaa.vercel.app/nested-dropdown), I am seeing undefined. Did you test that the event and items were coming through?

<img width="1440" alt="Screenshot 2023-01-14 at 08 35 42" src="https://user-images.githubusercontent.com/16717394/212423733-a0dc39c9-bd41-499f-8779-84990d1a44cd.png">

2023-01-13 21:54 UTC, steviebaa commented on apps/docs/src/pages/NestedDropdownPage.tsx
> +					) => console.log('Save As > Option 1 clicked'),
add `event, item` to the log for consistency

2023-01-13 21:54 UTC, steviebaa commented on apps/docs/src/pages/NestedDropdownPage.tsx
> +					) => console.log('Save As > Option 2 clicked'),
add `event, item` to the log for consistency

2023-01-13 21:54 UTC, steviebaa commented on apps/docs/src/pages/NestedDropdownPage.tsx
> +							) => console.log('Export > FT1 > O1 clicked'),
add `event, item` to the log for consistency

2023-01-13 21:54 UTC, steviebaa commented on apps/docs/src/pages/NestedDropdownPage.tsx
> +							) => console.log('Export > FT1 > O2 clicked'),
add `event, item` to the log for consistency

2023-01-13 21:54 UTC, steviebaa commented on apps/docs/src/pages/NestedDropdownPage.tsx
> +					) => console.log('Export > FT2 clicked'),
add `event, item` to the log for consistency

2023-01-13 21:54 UTC, steviebaa commented on packages/mui-nested-menu/src/definitions.ts
> +import { SxProps } from "@mui/system/styleFunctionSx/styleFunctionSx";
revert the changes to quotes.

2023-01-13 21:54 UTC, steviebaa commented on packages/mui-nested-menu/src/definitions.ts
> +    uid?: string;
revert the changes to indentation.

2023-01-17 17:08 UTC, YASHBRO commented
Sorry, @steviebaa for the delay.
I am occupied with my exams, I'll resolve these as soon as I'm done with them, that'll take 2-3 days.

2023-02-08 02:25 UTC, steviebaa commented
Hey @YASHBRO are you able to wrap this one up?

I will try to do a sweep on the codebase sometime soon to clean it up and it will likely create a few conflicts.

If you don't have time then I can finish it up but I'm not sure you'll get the credit as I'll need to make a new branch.

2023-02-08 14:44 UTC, YASHBRO commented
Hello @steviebaa 
Sorry, it slipped out of my mind.
I'll wrap it up by tonight

2023-02-08 17:36 UTC, YASHBRO commented
> Just a few minor changes @YASHBRO
> 
> Another note, when clicking the New item in the first dropdown on the [preview page](https://mui-nested-menu-6zkzw2lko-steviebaa.vercel.app/nested-dropdown), I am seeing undefined. Did you test that the event and items were coming through?
> 
> <img alt="Screenshot 2023-01-14 at 08 35 42" width="1440" src="https://user-images.githubusercontent.com/16717394/212423733-a0dc39c9-bd41-499f-8779-84990d1a44cd.png">

I am not able to replicate this error in my local machine, it works fine in my local machine but gives `undefined` in this preview link

2023-02-10 02:07 UTC, merged

2023-02-10 02:08 UTC, steviebaa commented
Thanks for getting this done Yash.